### ISSUE TITLE
FMUv5x/FMUv6 bootloader ITCM

### ISSUE THREAD

**Issue by dagar** [PX4/PX4-Bootloader#131]
For FMUv6 let's use ITCM (flash accelerator) from the beginning.

https://github.com/PX4/Bootloader/issues/126
https://github.com/PX4/Bootloader/tree/pr-itcm_hacks

**Comment by dagar** [comment]
Also applies to FMUv5x.

**Comment by davids5** [comment]
@dagar - H7 what a bummer the ART is not available on the STM32H74xx series.  We have 64K of ITCM and will have to use locate statements to place code into ITCM.

We can use it on the V5X (F7)

**Comment by LorenzMeier** [comment]
v6X is in the PX4 tree now.
