### ISSUE TITLE
Reserve Board ID 66

### ISSUE THREAD

**Issue by auturgy** [PX4/PX4-Bootloader#206]
Just a note to document that a vendor is using Board ID 66. It’s a closed PX4 fork, and for some reason they don’t want to PR, but ideally we need to document that the ID is in use.

**Comment by davids5** [comment]
@auturgy see https://github.com/PX4/PX4-Bootloader/pull/207

**Comment by auturgy** [comment]
Thanks David

**Comment by davids5** [comment]
Closed by https://github.com/PX4/PX4-Bootloader/issues/206
