### ISSUE TITLE
bootloader's uart update is not ok

### ISSUE THREAD

**Issue by yazhouren2012** [PX4/PX4-Bootloader#84]
hi, when i use usb to update nuttx, it's ok,
but when i use uart to update nuttx, it's not ok, so i debug the bootloader, i find that the function uart_cout() can't output anything, may be there is somewrong with this serial port 2.

**Comment by yazhouren2012** [comment]
MY hardware is pixhawk v2

**Comment by kenshin1988** [comment]
USART2 upload not working on Pixhawk4(TELEM1) with px_uploader.py.
Works well on USB using px_uploader.py. Anything we are missing? Repeated message showing
"If the board does not respond, unplug and replug the USB connector"

**Comment by kenshin1988** [comment]
I compiled and updated the FMU bootloader and tried to program again. I am able to go a step ahead now. Erase is completed with 100%. Program gets stuck at 0% and exits after a while with the message "ERROR: unexpected 18 instead of ISYNC"

**Comment by LorenzMeier** [comment]
Closing as stale.

**Comment by jlecoeur** [comment]
This is still an issue as of today. I suggest reopening.
@LorenzMeier @davids5 is UART bootlader functional on FMUv5 and FMUv5x ?

**Comment by davids5** [comment]
AFAIK yes. 

V5 it is on USART2_TELEM1 115200 BPS (not tested recently) Reopening for testing.
V5X  UART5_TELEM2            1500000BPS (Tested recently)

**Comment by jlecoeur** [comment]
solved in https://github.com/PX4/PX4-Autopilot/pull/16766
